### ISSUE TITLE
Projects Upgrade

### ISSUE THREAD

**Issue by MarcScott** [raspberrypilearning/chatbot#115]
## Before
- [x] Check if project could be archived
- [x] Check and resolve any outstanding issues
- [x] Check and resolve any outstanding pull requests
- [x] Check branch and master are equal

## Projects site
- [x] Check meta data has been included in the projects site from the meta.yml

## Meta
- [x] Increment version number
- [x] Update last tested date
- [x] Remove redundant meta tags (ingredient, duration, theme, curriculum, interest, site area, hardware, software)
- [x] Remove step numbers from meta (and any step names)

## Directory structure and files
- [x] `resources` directory containing all need assets
- [x] `solutions` directory containing all needed solutions
- [x] Add license.md if not exist

## Step 1
- [x] Place resources and solution into a zip (name-of-repo-file.ext)
- [x] Add license.md if not exist
- [x] Add interactive showcase of project or GIF to step 1
- [x] Add instructions for engaging with showcase before the showcase embed
- [x] "What you will learn" inside a collapse
- [x] "What you will need" inside a collapse
  - [x] Contains a list of hardware
  - [x] Contains a list of software
  - [x] Contains a link to the rpf.io/reponame-resources directory (use www.gitzip.com/ to generate long 
- [x] "Additional notes for educators" inside a collapse
  - [x] Contains a link to the rpf.io/reponame-solutions directory (use www.gitzip.com/ to generate long link and then shortlink it)
  - [x] “If you need to print this project, please use the printer-friendly version.”

## Step 2
- [x] Collapse content "Getting Started" if needed
  - [x] Contains starter code/links for Offline/online Pi/No Pi projects

## Tasks
- [x] Where learner is asked to do something use the ` ``` task ``` ` syntax

## Code
- [x] Add image of sprite above the code block it is referring to if Scratch
- [x] Screenshots replaced with [markdown](https://docs.google.com/document/d/1w7s9TzCj3lVf-rh4umQlLyN8e_wbg9ptZizmQPvfwHw/edit#heading=h.6jpkqdmev6a4)
- [x] If project is in Code Club book - check that the code matches

## Hints
- [x] 1 per step max

## Ingredients
- [x]  1 per step max

## Challenges
- [x] Each Challenge has it's own step
- [x] Must have challenge at end of project
- [x] Challenge can be skipped and project still completed

## Fall-backs
- [x] For all animated and embedded content include` ````--- no-print ---``` ` and ` ```print-only``` `sections

## Embeds
- [x] Check Scratch and Trinket embeds use official account

## Translations
- [ ] Open issue for Nina citing that the project has been changed

**Comment by martinohanlon** [comment]
Done.
